services:
  - type: web
    name: zenithive-backend
    env: go
    region: oregon
    plan: free
    branch: main
    buildCommand: |
      go mod download
      go build -o ums-backend main.go
    startCommand: ./ums-backend
    envVars:
      - key: DB_URL
        sync: false
      - key: JWT_SECRET
        sync: false
      - key: PORT
        value: 8082
      - key: RESEND_API_KEY
        sync: false
      - key: RESEND_FROM
        sync: false
    autoDeploy: true
    healthCheckPath: /api/auth/login
